# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-18 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200518_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
