# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-20 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20200518_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='publication_date',
            field=models.DateField(),
        ),
    ]
